FROM scrapejob-frontend

WORKDIR /app
ENV NODE_ENV=production
ENV HOSTNAME=0.0.0.0
ENV NEXT_TELEMETRY_DISABLED=1

COPY public ./public
COPY .next/standalone/server.js ./server.js
COPY .next/standalone/package.json ./package.json
COPY .next/standalone/src ./src
COPY .next/standalone/.next ./.next
COPY .next/static ./.next/static

EXPOSE 3000
CMD ["node", "server.js"]
