<?php

namespace Database\Seeders;

use App\Models\Page;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class PageSeeder extends Seeder
{
    public function run(): void
    {
        $pages = [
            ['title' => 'Tentang Lowonganku', 'status' => 'published', 'summary' => 'Kenali visi & misi platform Lowonganku dalam menghubungkan talenta dengan perusahaan.'],
            ['title' => 'Kebijakan Privasi', 'status' => 'published', 'summary' => 'Bagaimana kami memproses & melindungi data personal pengguna.'],
            ['title' => 'Syarat & Ketentuan', 'status' => 'published', 'summary' => 'Aturan penggunaan platform Lowonganku bagi pencari kerja dan perusahaan.'],
            ['title' => 'FAQ Pencari Kerja', 'status' => 'published', 'summary' => 'Pertanyaan paling sering diajukan oleh pencari kerja.'],
            ['title' => 'FAQ Perusahaan', 'status' => 'published', 'summary' => 'Panduan lengkap untuk perusahaan yang ingin memasang lowongan.'],
            ['title' => 'Panduan Melamar Kerja', 'status' => 'published', 'summary' => 'Tips efektif melamar melalui Lowonganku.'],
            ['title' => 'Karier di Lowonganku', 'status' => 'draft', 'summary' => 'Bergabunglah bersama tim yang membangun masa depan rekrutmen di Indonesia.'],
            ['title' => 'Media Kit', 'status' => 'draft', 'summary' => 'Aset resmi Lowonganku untuk keperluan media & pers.'],
            ['title' => 'Kontak', 'status' => 'published', 'summary' => 'Hubungi tim Lowonganku untuk pertanyaan atau kemitraan.'],
            // Blog Articles
            [
                'title' => '10 Tips Sukses Wawancara Kerja Online di Era Digital',
                'status' => 'published',
                'summary' => 'Wawancara kerja online kini menjadi standar baru. Pelajari tips dan trik agar performa terbaikmu terpancar saat interview via video call.',
                'content' => '<p>Wawancara kerja online semakin menjadi standar dalam proses rekrutmen. Menurut survei terbaru, lebih dari 70% perusahaan di Indonesia kini menggunakan video interview sebagai tahap awal seleksi. Dengan persiapan yang tepat, kamu bisa tampil percaya diri dan meninggalkan kesan positif pada rekruter.</p><h3>1. Persiapan Teknis yang Matang</h3><p>Pastikan koneksi internet stabil minimal 10 Mbps, kamera berfungsi dengan baik, dan ruangan memiliki pencahayaan yang cukup. Uji perangkatmu sehari sebelum wawancara — cek mikrofon, speaker, dan background. Gunakan headset untuk mengurangi noise lingkungan.</p><h3>2. Riset Mendalam tentang Perusahaan</h3><p>Kunjungi website resmi, baca laporan tahunan terbaru, dan cek media sosial perusahaan. Pahami visi, misi, dan projek terkini mereka. Tunjukkan bahwa kamu benar-benar tertarik dengan posisi yang dilamar dan bisa memberikan kontribusi nyata.</p><h3>3. Berpakaian Profesional dari Kepala hingga Pinggang</h3><p>Meskipun wawancara dari rumah, berpakaian rapi menunjukkan keseriusanmu. Pilih warna solid yang tidak mencolok di kamera. Hindari motif ramai yang bisa mengganggu fokus pewawancara.</p><h3>4. Kontrol Bahasa Tubuh</h3><p>Tatap kamera saat berbicara (bukan layar), duduk tegak, dan tunjukkan antusiasme melalui ekspresi wajah. Gunakan gesture tangan secukupnya untuk menekankan poin penting. Jangan lupa tersenyum natural.</p><h3>5. Siapkan Lingkungan yang Tenang</h3><p>Beri tahu anggota keluarga atau teman serumah tentang jadwal wawancara. Matikan notifikasi HP dan aplikasi di laptop. Pastikan background terlihat rapi dan profesional.</p><h3>6. Jawab dengan Metode STAR</h3><p>Untuk pertanyaan behavioral, gunakan metode STAR (Situation, Task, Action, Result). Ceritakan pengalamanmu secara terstruktur sehingga mudah dipahami dan meyakinkan.</p><h3>7. Siapkan Pertanyaan untuk Pewawancara</h3><p>Ajukan pertanyaan tentang budaya perusahaan, tim yang akan kamu masuki, atau tantangan di posisi tersebut. Ini menunjukkan ketertarikanmu dan bahwa kamu sudah berpikir serius tentang posisi ini.</p><h3>8. Kirim Follow-Up dalam 24 Jam</h3><p>Setelah wawancara, kirim email terima kasih yang singkat dan profesional. Sebutkan momen spesifik dari wawancara yang menurutmu menarik. Ini akan membuatmu lebih diingat oleh rekruter.</p>',
            ],
            [
                'title' => 'Membangun Personal Branding untuk Pencari Kerja',
                'status' => 'published',
                'summary' => 'Personal branding yang kuat bisa menjadi pembeda di pasar kerja yang kompetitif. Kenali cara membangun citra profesional yang menarik bagi recruiter.',
                'content' => '<p>Di era digital, personal branding bukan lagi opsional — melainkan kebutuhan. Data menunjukkan bahwa 87% rekruter menggunakan LinkedIn untuk mengevaluasi kandidat. Personal branding yang kuat membantumu menonjol di antara ribuan pelamar lain dan membuka peluang yang bahkan tidak pernah kamu bayangkan.</p><h3>Optimasi Profil LinkedIn</h3><p>Gunakan foto profesional dengan background bersih. Tulis headline yang compelling — bukan hanya jabatan, tapi value propositionmu. Contoh: "Frontend Developer | Membantu Startup Membangun UI yang Conversion-Driven." Jelaskan pengalamanmu dengan achievement-oriented, gunakan angka dan hasil konkret.</p><h3>Bangun Portofolio Online yang Menarik</h3><p>Tunjukkan hasil kerja terbaikmu melalui website pribadi atau platform portofolio. Untuk developer, GitHub dengan README yang rapi adalah wajib. Untuk designer, Behance atau Dribbble dengan case study yang detail akan sangat berharga. Sertakan konteks masalah, proses solusi, dan hasil yang terukur.</p><h3>Konsisten di Media Sosial Profesional</h3><p>Bagikan insight dan konten relevan di bidangmu secara konsisten. Tulis thread di Twitter/X tentang pelajaran dari proyek terakhir, atau posting artikel singkat di LinkedIn. Tunjukkan thought leadership melalui tulisan atau diskusi profesional. Kunci utamanya adalah konsistensi — minimal 2-3 posting per minggu.</p><h3>Bangun Jaringan yang Bermakna</h3><p>Jangan hanya mengumpulkan koneksi. Berikan value terlebih dahulu — bantu orang lain, berikan komentar yang konstruktif, dan share knowledge. Jaringan yang bermakna akan membuka pintu peluang yang tidak bisa kamu akses sendiri.</p><h3>Jaga Konsistensi di Semua Platform</h3><p>Pastikan pesan, tone, dan visual brandingmu konsisten di LinkedIn, portfolio website, GitHub, dan media sosial lainnya. Inkonsistensi bisa membingungkan rekruter dan mengurangi kredibilitasmu.</p>',
            ],
            [
                'title' => 'Memahami Gaji dan Benefits: Panduan Lengkap untuk Job Seeker',
                'status' => 'published',
                'summary' => 'Jangan hanya fokus pada gaji pokok. Pelajari komponen benefits lainnya yang bisa meningkatkan kualitas hidupmu secara keseluruhan.',
                'content' => '<p>Saat menerima tawaran kerja, banyak job seeker yang hanya fokus pada angka gaji pokok. Padahal, ada banyak komponen benefits lain yang perlu diperhatikan. Memahami total compensation package bisa membuatmu menghemat jutaan rupiah per tahun dan meningkatkan kualitas hidup secara signifikan.</p><h3>1. Gaji Pokok vs Total Compensation</h3><p>Total compensation mencakup gaji pokok, bonus tahunan, tunjangan transportasi dan makan, asuransi kesehatan, dan hak saham (jika ada). Perbandingan ini memberikan gambaran lebih akurat tentang nilai kompensasimu. Sebuah perusahaan dengan gaji pokok lebih rendah tapi benefits lengkap bisa jadi lebih menguntungkan.</p><h3>2. Tunjangan Kesehatan</h3><p>Asuransi kesehatan adalah salah satu benefit paling berharga. Periksa apakah perusahaan mencakup rawat inap, rawat jalan, gigi, dan mata. Beberapa perusahaan juga menyediakan benefit kesehatan mental seperti konseling gratis. Nilai asuransi kesehatan swasta bisa mencapai Rp 15-30 juta per tahun.</p><h3>3. Tunjangan Transportasi dan Makan</h3><p>Tunjangan ini mungkin terlihat kecil, tapi jika dihitung setahun bisa mencapai Rp 24-48 juta. Beberapa perusahaan juga menyediakan shuttle bus atau subsidi parkir yang bisa menghemat pengeluaranmu secara signifikan.</p><h3>4. Work-Life Balance</h3><p>Fleksibilitas kerja, remote work option, dan jumlah cuti tahunan adalah faktor yang sangat mempengaruhi kualitas hidup. Perusahaan dengan kebijakan hybrid work yang fleksibel bisa menghemat waktu commuting 2-3 jam per hari. Hitung nilai waktu ini dalam evaluasimu.</p><h3>5. Bonus dan Insentif</h3><p>Pahami struktur bonus — apakah berdasarkan performa individu, tim, atau perusahaan? Tanyakan rata-rata bonus yang diterima karyawan dalam 2-3 tahun terakhir. Bonus 1-2x gaji per tahun adalah standar di banyak perusahaan besar.</p><h3>6. Pengembangan Karier</h3><p>Perhatikan apakah perusahaan menyediakan budget untuk pelatihan, sertifikasi, atau konferensi. Benefit ini bisa bernilai puluhan juta per tahun dan investasi terbaik untuk jangka panjang kariermu.</p>',
            ],
            [
                'title' => 'Fresh Graduate? Ini Cara Efektif Mencari Pekerjaan Pertama',
                'status' => 'published',
                'summary' => 'Mencari pekerjaan pertama sebagai fresh graduate bisa menjadi tantangan. Simak strategi efektif untuk memulai kariermu.',
                'content' => '<p>Lulus dari universitas adalah pencapaian besar, namun mencari pekerjaan pertama bisa terasa menakutkan. Data BPS menunjukkan bahwa tingkat pengangguran terdidik masih cukup tinggi. Berikut strategi yang sudah terbukti efektif membantu fresh graduate mendapatkan pekerjaan pertama mereka.</p><h3>1. Manfaatkan Program Magang secara Maksimal</h3><p>Banyak perusahaan besar menawarkan program magang yang bisa menjadi jalan masuk ke posisi full-time. Jangan remehkan pengalaman magang — 60% magang di perusahaan besar berujung pada penawaran kerja tetap. Pilih magang yang memberikan exposure ke projek nyata, bukan hanya tugas administratif.</p><h3>2. Bangun Portofolio yang Bercerita</h3><p>Meskipun belum punya pengalaman kerja formal, portofolio proyek pribadi, tugas akhir, atau volunteer work bisa menunjukkan kemampuanmu. Yang terpenting bukan jumlah proyeknya, tapi bagaimana kamu menceritakan proses dan hasilnya. Gunakan format case study: masalah, pendekatan, hasil.</p><h3>3. Jaringan, Jaringan, Jaringan</h3><p>Hadiri job fair, seminar industri, dan event networking. Penelitian menunjukkan bahwa 70% lowongan tidak dipublikasikan secara terbuka — mereka terisi melalui referral dan jaringan profesional. Mulailah membangun jaringan sebelum lulus.</p><h3>4. Sesuaikan Resume untuk Setiap Lamaran</h3><p>Tailor resume untuk setiap posisi yang dilamar. Highlight skill dan pengalaman yang relevan dengan job description. Gunakan kata kunci yang sama dengan yang ada di posting lowongan. ATS (Applicant Tracking System) akan memindai resume berdasarkan kata kunci ini.</p><h3>5. Persiapkan Diri untuk Tes Online</h3><p>Banyak perusahaan menggunakan tes online sebagai tahap awal seleksi. Latih kemampuan numerical reasoning, verbal reasoning, dan logical reasoning. Banyak resource gratis di internet yang bisa membantumu berlatih.</p><h3>6. Jangan Takut Memulai dari yang Kecil</h3><p>Perusahaan kecil atau startup sering memberikan tanggung jawab yang lebih besar kepada junior. Pengalaman di perusahaan kecil bisa mempercepat pembelajaranmu dan menjadi stepping stone untuk karier yang lebih baik di masa depan.</p>',
            ],
            [
                'title' => 'Work from Home: Tips Produktif Bekerja dari Rumah',
                'status' => 'published',
                'summary' => 'Bekerja dari rumah membutuhkan disiplin khusus. Pelajari cara tetap produktif dan menjaga work-life balance saat WFH.',
                'content' => '<p>Work from Home (WFH) bukan lagi sekadar tren — sudah menjadi model kerja yang diterima secara luas. Survei McKinsey menunjukkan bahwa 58% pekerja Amerika memiliki opsi WFH minimal satu hari per minggu. Namun, bekerja dari rumah membutuhkan disiplin dan strategi khusus agar tetap produktif dan tidak burnout.</p><h3>1. Ciptakan Ruang Kerja yang Terpisah</h3><p>Siapkan sudut khusus yang nyaman dan minim gangguan untuk bekerja. Pisahkan area kerja dari area istirahat — ini membantu otakmu beralih antara mode kerja dan mode santai. Jika tidak memiliki ruang terpisah, gunakan trik visual seperti meja khusus atau partisi sederhana.</p><h3>2. Tetapkan Rutinitas yang Konsisten</h3><p>Bangun pada jam yang sama setiap hari, mandi, dan berpakaian seolah akan pergi ke kantor. Ini membantu otak beralih ke mode kerja. Buat jadwal yang jelas termasuk waktu istirahat dan makan siang. Jangan lupa untuk benar-benar berhenti bekerja di akhir hari.</p><h3>3. Gunakan Teknologi yang Tepat</h3><p>Manfaatkan tools kolaborasi seperti Slack untuk komunikasi harian, Zoom/Google Meet untuk meeting, dan Trello/Notion untuk project management. Atur notifikasi agar tidak terganggu setiap saat — cek pesan pada waktu yang terjadwal.</p><h3>4. Terapkan Teknik Time Blocking</h3><p>Bagi haramu menjadi blok-blok waktu untuk tugas yang berbeda. Misalnya, blok pagi untuk deep work tanpa gangguan, blok siang untuk meeting dan kolaborasi, blok sore untuk email dan tugas administratif. Ini membantu menjaga fokus dan menghindari multitasking.</p><h3>5. Jaga Kesehatan Fisik dan Mental</h3><p>Berdiri dan bergerak setiap 60-90 menit. Lakukan stretching ringan atau jalan singkat. Konsumsi makanan bergizi dan cukup air. Jangan lupa menjaga hubungan sosial — WFH bisa terasa isolasi jika tidak dikelola dengan baik.</p><h3>6. Komunikasi yang Efektif dengan Tim</h3><p>Over-communication lebih baik daripada under-communication saat WFH. Update status pekerjaan secara berkala, beri tahu tim jika ada blocker, dan jangan ragu untuk bertanya. Gunakan async communication untuk hal yang tidak urgent.</p>',
            ],
            [
                'title' => 'Mengenal Berbagai Jenis Kontrak Kerja di Indonesia',
                'status' => 'published',
                'summary' => 'Pahami perbedaan PKWT, PKWTT, dan jenis kontrak lainnya agar kamu tahu hak dan kewajibanmu sebagai pekerja.',
                'content' => '<p>Memahami jenis kontrak kerja sangat penting untuk melindungi hak-hakmu sebagai pekerja. Sayangnya, banyak pekerja yang tidak membaca detail kontrak sebelum menandatangani. Berikut penjelasan lengkap tentang berbagai jenis kontrak kerja di Indonesia berdasarkan UU Ketenagakerjaan.</p><h3>PKWTT (Perjanjian Kerja Waktu Tidak Tertentu)</h3><p>Kontrak permanen dengan masa kerja tidak ditentukan. Pekerja mendapat perlindungan penuh sesuai UU Ketenagakerjaan No. 13/2003. Keuntungan utama termasuk pesangon yang lebih besar, jaminan kerja jangka panjang, dan benefit yang lebih lengkap. PKWTT harus disertai masa percobaan maksimal 3 bulan.</p><h3>PKWT (Perjanjian Kerja Waktu Tertentu)</h3><p>Kontrak dengan jangka waktu tertentu, maksimal 5 tahun termasuk perpanjangan. PKWT hanya bisa diberikan untuk pekerjaan yang bersifat sementara, sekali selesai, atau musiman. Setelah masa berakhir, perusahaan harus mengonversi menjadi PKWTT jika pekerjaan masih dibutuhkan. PKWT tidak boleh disertai masa percobaan.</p><h3>Kontrak Freelance dan Outsourcing</h3><p>Perjanjian kerja lepas (freelance) mengatur hubungan kerja untuk proyek tertentu dengan pembayaran per proyek atau per periode. Pekerja outsourcing dipekerjakan oleh perusahaan penyedia layanan, bukan oleh perusahaan tempat mereka bekerja. Keduanya memiliki hak yang berbeda dengan karyawan tetap.</p><h3>Apa yang Harus Diperhatikan dalam Kontrak</h3><p>Periksa detail gaji, tunjangan, jam kerja, lokasi kerja, dan klausa non-kompetisi. Pastikan ada klausul tentang prosedur pemutusan hubungan kerja (PHK) dan pesangon. Jangan ragu untuk bertanya jika ada poin yang tidak jelas — kontrak yang baik melindungi kedua belah pihak.</p>',
            ],
            [
                'title' => 'Cara Negosiasi Gaji yang Efektif Tanpa Ragu',
                'status' => 'published',
                'summary' => 'Negosiasi gaji adalah skill penting yang sering dihindari job seeker. Pelajari strategi untuk mendapatkan kompensasi yang layak.',
                'content' => '<p>Banyak job seeker yang merasa tidak nyaman saat negosiasi gaji. Padahal, negosiasi yang baik bisa meningkatkan gaji awal hingga 10-20%. Dalam 5 tahun, selisih ini bisa bernilai ratusan juta rupiah. Berikut strategi negosiasi gaji yang efektif dan profesional.</p><h3>1. Lakukan Riset Gaji Pasar</h3><p>Sebelum negosiasi, ketahui rentang gaji untuk posisi dan level pengalamanmu di industri tersebut. Gunakan platform seperti Glassdoor, JobStreet, atau survei gaji dari Kelly Services dan Robert Walters. Data adalah senjata terbaik dalam negosiasi.</p><h3>2. Tunda Pembahasan Gaji selama Mungkin</h3><p>Biarkan perusahaan menyebutkan angka terlebih dahulu. Jika ditanya tentang ekspektasi gaji di awal, berikan rentang berdasarkan risetmu, atau tanyakan budget yang dialokasikan untuk posisi ini. Semakin lama mereka mengenalmu, semakin besar leverage-mu.</p><h3>3. Fokus pada Nilai, Bukan Kebutuhan</h3><p>Jangan negosiasi berdasarkan kebutuhan pribadi ("Saya butuh gaji segini karena..."). Sebaliknya, fokus pada nilai yang bisa kamu berikan. Contoh: "Berdasarkan pengalaman saya memimpin tim 10 orang dan meningkatkan efisiensi 30%, saya percaya kompensasi yang sesuai adalah..."</p><h3>4. Negosikan Total Package</h3><p>Jika gaji pokok tidak bisa dinaikkan, negosikan komponen lain: signing bonus, review gaji lebih cepat, tunjangan tambahan, hari cuti ekstra, atau opsi remote work. Total compensation package bisa jadi lebih berharga daripada gaji pokok yang lebih tinggi.</p><h3>5. Gunakan Teknik Silence</h3><p>Setelah menyampaikan angka, diam sejenak. Jangan langsung mengisi keheningan dengan penjatahan atau menurunkan angka. Keheningan yang nyaman menunjukkan kepercayaan diri dan memberi ruang bagi pihak lain untuk merespons.</p><h3>6. Bersiap untuk Walk Away</h3><p>Ketahui batas bawahmu dan bersiap untuk menolak jika tawaran tidak sesuai. Memiliki BATNA (Best Alternative to Negotiated Agreement) memberimu kekuatan. Terkadang, menolak tawaran yang tidak adil membuka peluang untuk tawaran yang lebih baik di tempat lain.</p>',
            ],
            [
                'title' => 'Skill Digital yang Paling Dicari Perusahaan di 2025',
                'status' => 'published',
                'summary' => 'Dunia kerja terus berevolusi. Kenali skill digital yang paling diminati perusahaan dan cara menguasainya.',
                'content' => '<p>Revolusi digital mengubah lanskap dunia kerja secara fundamental. World Economic Forum memperkirakan bahwa 44% skill inti pekerja akan berubah dalam 5 tahun ke depan. Berikut skill digital yang paling dicari perusahaan di Indonesia dan global pada 2025.</p><h3>1. Data Analysis dan Data Literacy</h3><p>Kemampuan membaca, menganalisis, dan mengambil keputusan berdasarkan data menjadi skill wajib di hampir semua industri. Kuasai tools seperti Excel tingkat lanjut, SQL, dan dasar-dasar Python untuk analisis data. Platform seperti Google Data Analytics Certificate bisa menjadi starting point yang baik.</p><h3>2. Artificial Intelligence dan Machine Learning</h3><p>Bukan hanya untuk engineer — pemahaman dasar tentang AI dan cara menggunakannya dalam pekerjaan sehari-hari sangat bernilai. Pelajari cara menggunakan tools AI seperti ChatGPT, Copilot, atau Midjourney untuk meningkatkan produktivitas. Untuk technical roles, kuasai framework seperti TensorFlow atau PyTorch.</p><h3>3. Cloud Computing</h3><p>Sertifikasi cloud dari AWS, Google Cloud, atau Azure sangat diminati. Pemahaman tentang infrastruktur cloud, deployment, dan manajemen cost adalah skill yang sangat terukur dan bernilai tinggi di pasar kerja.</p><h3>4. Cybersecurity</h3><p>Dengan meningkatnya ancaman siber, permintaan untuk tenaga ahli keamanan siber terus meningkat. Dasar-dasar cybersecurity seperti network security, ethical hacking, dan compliance adalah investasi yang sangat baik untuk karier jangka panjang.</p><h3>5. UI/UX Design</h3><p>Kemampuan merancang pengalaman pengguna yang intuitif dan menarik sangat dicari, terutama di industri tech dan startup. Kuasai tools seperti Figma, dan pahami prinsip design thinking dan user research.</p><h3>6. Digital Marketing dan SEO</h3><p>Pemahaman tentang digital marketing, SEO, content strategy, dan analytics sangat bernilai. Perusahaan dari semua ukuran membutuhkan tenaga ahli yang bisa mengoptimalkan kehadiran digital mereka dan menghasilkan leads berkualitas.</p><h3>Cara Mulai Belajar</h3><p>Manfaatkan platform pembelajaran online seperti Coursera, Dicoding, atau MySkill. Fokus pada satu skill pada satu waktu, bangun projek nyata, dan dapatkan sertifikasi. Konsistensi belajar 1-2 jam per hari lebih efektif daripada marathon sesekali.</p>',
            ],
            [
                'title' => 'Panduan Lengkap Membuat CV yang Dilirik ATS',
                'status' => 'published',
                'summary' => 'ATS adalah gerbang pertama yang harus kamu lalui. Pelajari cara membuat CV yang lolos screening otomatis dan menarik perhatian rekruter.',
                'content' => '<p>Applicant Tracking System (ATS) digunakan oleh lebih dari 95% perusahaan Fortune 500 dan semakin banyak perusahaan di Indonesia. ATS memindai CV-mu sebelum dibaca oleh manusia. Jika CV-mu tidak dioptimasi untuk ATS, kamu bisa kehilangan peluang bahkan sebelum rekruter melihatnya.</p><h3>Apa itu ATS dan Cara Kerjanya</h3><p>ATS adalah software yang memindai, mengkategorikan, dan memeringkat CV berdasarkan relevansi dengan job description. Sistem ini mencari kata kunci spesifik, kualifikasi, dan pengalaman yang sesuai. CV yang tidak lolos ATS tidak akan pernah sampai ke meja rekruter.</p><h3>Format CV yang ATS-Friendly</h3><p>Gunakan format standar tanpa tabel, kolom, atau grafik yang rumit. ATS kesulitan membaca elemen desain kompleks. Pilih font standar seperti Arial, Calibri, atau Times New Roman. Gunakan heading standar seperti "Pengalaman Kerja", "Pendidikan", dan "Skills".</p><h3>Optimasi Kata Kunci</h3><p>Baca job description dengan teliti dan identifikasi kata kunci yang digunakan. Masukkan kata kunci ini secara natural dalam CV-mu — di deskripsi pengalaman, skills section, dan summary. Jangan keyword stuffing; pastikan CV tetap terbaca secara natural oleh manusia.</p><h3>Struktur CV yang Efektif</h3><p>Mulai dengan professional summary yang ringkas (3-4 baris), diikuti pengalaman kerja dengan achievement terukur, lalu pendidikan, dan skills. Untuk setiap pengalaman kerja, gunakan bullet points yang dimulai dengan action verb dan diakhiri dengan hasil yang terukur.</p><h3>Contoh Achievement yang Terukur</h3><p>Bukan: "Bertanggung jawab atas penjualan."<br>Tapi: "Meningkatkan penjualan regional 35% dalam 6 bulan melalui strategi cold calling dan partnership dengan 12 klien baru."<br>Angka dan hasil konkret membuat CV-mu lebih menarik dan meyakinkan.</p><h3>Hal yang Harus Dihindari</h3><p>Jangan menggunakan header/footer untuk informasi penting (ATS sering tidak membacanya). Hindari singkatan yang tidak umum. Jangan sertakan foto, tanggal lahir, atau informasi pribadi yang tidak relevan — ini bisa menjadi bias dan tidak ditampilkan oleh ATS modern.</p>',
            ],
            [
                'title' => 'Menghadapi Penolakan Kerja: Cara Bangkit dan Terus Melangkah',
                'status' => 'published',
                'summary' => 'Penolakan adalah bagian dari proses pencarian kerja. Pelajari cara mengelola emosi dan mengubah penolakan menjadi motivasi.',
                'content' => '<p>Mendapat email penolakan setelah wawancara yang sudah kamu persiapkan dengan matang memang menyakitkan. Namun, penolakan adalah bagian tak terpisahkan dari proses pencarian kerja. Bahkan orang-orang sukses seperti Steve Jobs, Oprah Winfrey, dan J.K. Rowling pernah ditolak berkali-kali sebelum akhirnya berhasil.</p><h3>Kenapa Penolakan Terjadi</h3><p>Penolakan tidak selalu berarti kamu tidak kompeten. Bisa jadi ada kandidat yang lebih cocok secara spesifik, budget perusahaan berubah, atau posisi tersebut diinternal fill. Memahami bahwa penolakan bukan penilaian pribadi membantumu memproses emosi dengan lebih baik.</p><h3>Berikan Waktu untuk Merasakan</h3><p>Jangan paksa dirimu untuk langsung "move on". Beri waktu untuk merasa kecewa — ini normal dan sehat. Bicara dengan teman atau keluarga yang dipercaya. Menulis jurnal juga bisa membantu memproses emosi dan mendapatkan perspektif baru.</p><h3>Minta Feedback yang Konstruktif</h3><p>Setelah emosi mereda, hubungi rekruter dan minta feedback secara profesional. Banyak perusahaan bersedia memberikan feedback singkat. Informasi ini sangat berharga untuk meningkatkan performa di wawancara berikutnya. Jangan defensif — terima feedback dengan terbuka.</p><h3>Evaluasi dan Perbaiki</h3><p>Review kembali setiap tahap seleksi. Apakah CV-mu sudah optimal? Apakah ada pertanyaan wawancara yang bisa kamu jawab lebih baik? Apakah ada skill yang perlu ditingkatkan? Buat daftar perbaikan konkret dan implementasikan sebelum melamar berikutnya.</p><h3>Tetap Rutin dan Terstruktur</h3><p>Jangan biarkan penolakan menghentikan momentummu. Tetap jadwalkan waktu untuk melamar, networking, dan belajar. Perlakukan pencarian kerja seperti pekerjaan — dengan jadwal, target, dan accountability. Konsistensi akan membuahkan hasil.</p><h3>Ubah Narasi Internal</h3><p>Ganti pikiran "Saya ditolak karena tidak cukup baik" dengan "Ini bukan kecocokan yang tepat, dan ada peluang lebih baik menunggu." Mindset growth membantumu melihat setiap penolakan sebagai pembelajaran, bukan kegagalan. Percaya bahwa proses ini akan membawamu ke tempat yang tepat.</p>',
            ],
        ];

        foreach ($pages as $item) {
            $slug = Str::slug($item['title']);
            Page::query()->updateOrCreate(
                ['slug' => $slug],
                [
                    'title' => $item['title'],
                    'status' => $item['status'],
                    'summary' => $item['summary'],
                    'content' => $item['content'] ?? "<p>{$item['summary']}</p><p>Konten halaman ini akan segera dilengkapi oleh tim editorial Lowonganku.</p>",
                    'seo_title' => $item['title'].' | Lowonganku',
                    'seo_description' => $item['summary'],
                    'published_at' => $item['status'] === 'published' ? now() : null,
                ],
            );
        }
    }
}
